[package]
name = "nf5"
version = "0.1.0"
authors = ["Bradford D. Boyle <bradford.d.boyle@gmail.com>"]
build = "build.rs"

[build-dependencies]
syntex = "0.42.*"
pnet_macros = "0.13.0"

[dependencies]
pcap = "0.5.7"
pnet = "0.16.0"
pnet_macros_support = "0.1.1"
